features = [
    # jets
    "jet_pt1", 
    "jet_eta1", 
    "jet_phi1", 
    "jet_m1", 
    "jet_bweight1", 
    "jet_pt2", 
    "jet_eta2", 
    "jet_phi2", 
    "jet_m2", 
    "jet_bweight2", 
    "jet_pt3", 
    "jet_eta3", 
    "jet_phi3", 
    "jet_m3", 
    "jet_bweight3", 
    # electrons
    "el_pt1", 
    "el_eta1", 
    "el_phi1", 
    "el_charge1", 
    "el_pt2", 
    "el_eta2", 
    "el_phi2", 
    "el_charge2", 
    # muons
    "mu_pt1", 
    "mu_eta1", 
    "mu_phi1", 
    "mu_charge1",
    "mu_pt2", 
    "mu_eta2", 
    "mu_phi2", 
    "mu_charge2",
    # other
    "met",
    "met_phi",
    "event_weight",
    "dsid"
]
