# Features should be listed in the same order they appear in the flat ntuple
features = [
    # jets
    "jet_pt1", 
    "jet_pt2", 
    "jet_pt3", 
    "jet_eta1", 
    "jet_eta2", 
    "jet_eta3", 
    "jet_phi1", 
    "jet_phi2", 
    "jet_phi3", 
    "jet_m1", 
    "jet_m2", 
    "jet_m3", 
    # leptons
    "lep_pt1", 
    "lep_pt2", 
    "lep_eta1", 
    "lep_eta2", 
    "lep_phi1", 
    "lep_phi2", 
    "lep_charge1", 
    "lep_charge2", 
    # other
    "n_jets",
    "n_bjets",
    "mjj",
    "mll",
    #"mt2",
    "pt_jj",
    "pt_ll",
    "dR_jj",
    "dR_ll",
    "dPhi_jj_met",
    "dPhi_ll_met",
    "dPhi_jj_ll",
    "met",
    "met_phi",
    "event_weight",
    "dsid"
]
